1. Python program to add two Matrices


In [9]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(X)):
 
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)


[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


2. Python program to multiply two matrices


In [13]:
import numpy as np
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
B = [[5,8,1],
    [6,7,3],
    [4,5,9]]

 
result= [[0,0,0],
         [0,0,0],
         [0,0,0]]
 
result = np.dot(A,B)
 
for r in result:
    print(r)

[114 160  60]
[74 97 73]
[119 157 112]


3. Python program for Matrix Product


In [16]:
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
     
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range (len(B)):
            result[i][j]+=A[i][k]*B[k][j]
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


4. Adding and Subtracting Matrices in Python


In [21]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
addition=np.add(A,B)
print("Addition of 2 Matrix is :",addition)
subtrac=np.subtract(A,B)
print("Subtraction of 2 Matrix is :",subtrac)

Addition of 2 Matrix is : [[ 5  7]
 [ 9 11]]
Subtraction of 2 Matrix is : [[-3 -3]
 [-3 -3]]


5. Transpose a matrix in Single line in Python


In [23]:
import numpy as np
matrix=[[1,2,3],[4,5,6]]
print(matrix)
print("\n")
print(np.transpose(matrix))

[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


6. Python | Matrix creation of n*n


In [24]:
n = 4
matrix = [list(range(1 + n * i, 1 + n * (i + 1))) for i in range(n)]
print("The created matrix of {} * {}: ".format(n,n))
for m in matrix:
    print(m)

The created matrix of 4 * 4: 
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


7. Python | Get Kth Column of Matrix


In [28]:
a = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
K = 2
  
res = [i[K] for i in a]
  
print("The Kth column of matrix is : " + str(res))

The Kth column of matrix is : [6, 10, 5]


8. Python – Vertical Concatenation in Matrix


In [40]:
test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]
print("The original list : " + str(test_list))
res = []
N = 0
while N != len(test_list):
    temp = ''
    for idx in test_list:
          

        try: temp = temp + idx[N]
        except IndexError: pass
    res.append(temp)
    N = N + 1
  
res = [ele for ele in res if ele]
  
print("List after column Concatenation : " + str(res))
        

The original list : [['Gfg', 'good'], ['is', 'for'], ['Best']]
List after column Concatenation : ['GfgisBest', 'goodfor']


9. Python program to check if a string is palindrome or not


In [ ]:
def isPalindrome(s):
    return s == s[::-1]
s = "malayalam"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")

10. Python program to check whether the string is Symmetrical or Palindrome

In [64]:
def isPalindrome(s):
    return s == s[::-1]
s =input("input a string")
ans = isPalindrome(s)
 
if ans:
    print("The string is a palindrome")
else:
    print("The string is not a palindrome")
def issymmetric(s):
    
    n=len(s)
    flag=0
    if n%2:
        mid=n//2+1
    else:
        mid=n//2
    start1=0
    end1=mid
    while(start1<mid and end1<n):
        if(s[start1]==s[end1]):
            start1=start1+1
            end1=end1+1
        else:
            flag=1
            break
    if flag==0:
        print("The string is symmetrical")
    else:
        print("The string is not symmetrical")

isPalindrome(s)
issymmetric(s)
    


input a stringamaama
The string is a palindrome
The string is symmetrical
